import http from "node:http";
import { readFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { extname, join } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { extractUrl, classify, inferContentType, parseSearchQuery, reviewScore } from "./src/core.mjs";
const PORT = Number(process.env.PORT || 4173); await mkdir("data", { recursive: true });
const db = new DatabaseSync(process.env.DB_PATH || "data/shicang.db");
db.exec(`CREATE TABLE IF NOT EXISTS collections (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL DEFAULT 'local-user',source TEXT NOT NULL DEFAULT 'douyin',platform TEXT NOT NULL DEFAULT 'douyin',content_type TEXT NOT NULL DEFAULT 'unknown',original_url TEXT NOT NULL DEFAULT '',raw_share_text TEXT NOT NULL DEFAULT '',title TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',category TEXT NOT NULL DEFAULT '其他',tags TEXT NOT NULL DEFAULT '[]',ocr_text TEXT NOT NULL DEFAULT '',imported_at TEXT NOT NULL,created_at TEXT NOT NULL,last_reviewed_at TEXT,review_count INTEGER NOT NULL DEFAULT 0,parse_status TEXT NOT NULL DEFAULT 'saved_basic',ai_summary TEXT,transcript TEXT,knowledge_items TEXT,embedding TEXT); CREATE TABLE IF NOT EXISTS collection_images (id INTEGER PRIMARY KEY AUTOINCREMENT,collection_id INTEGER NOT NULL,data_url TEXT NOT NULL,FOREIGN KEY(collection_id) REFERENCES collections(id) ON DELETE CASCADE); CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL DEFAULT 'local-user',name TEXT NOT NULL,rule_key TEXT,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,UNIQUE(user_id,name)); CREATE INDEX IF NOT EXISTS idx_collections_user_imported ON collections(user_id, imported_at DESC); CREATE INDEX IF NOT EXISTS idx_collections_category ON collections(user_id, category); CREATE INDEX IF NOT EXISTS idx_images_collection ON collection_images(collection_id); CREATE INDEX IF NOT EXISTS idx_categories_user_sort ON categories(user_id,sort_order);`);
const defaultCategories=[["AI","AI"],["找工作","找工作"],["美食","美食"],["小说","小说"],["其他","其他"]];if(db.prepare("SELECT COUNT(*) AS count FROM categories WHERE user_id=?").get("local-user").count===0){const insert=db.prepare("INSERT INTO categories (user_id,name,rule_key,sort_order,created_at) VALUES (?,?,?,?,?)"),now=new Date().toISOString();defaultCategories.forEach(([name,key],index)=>insert.run("local-user",name,key,index,now));}
const json=(res,status,value)=>{res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","expires":"0"});res.end(JSON.stringify(value));};
const readBody=async(req)=>{const chunks=[];for await(const chunk of req)chunks.push(chunk);return JSON.parse(Buffer.concat(chunks).toString()||"{}");};
const normalize=(value)=>value&&({...value,tags:JSON.parse(value.tags||"[]"),images:db.prepare("SELECT data_url FROM collection_images WHERE collection_id=? ORDER BY id").all(value.id).map(x=>x.data_url)}); const getAll=()=>db.prepare("SELECT * FROM collections WHERE user_id=? ORDER BY imported_at DESC").all("local-user").map(normalize);
const getCategories=()=>db.prepare("SELECT id,name,rule_key,sort_order FROM categories WHERE user_id=? ORDER BY sort_order,id").all("local-user");const resolveCategory=(suggested)=>getCategories().find(x=>x.rule_key===suggested)?.name||getCategories().find(x=>x.rule_key==="其他")?.name||"其他";
async function api(req,res,url){
 if(req.method==="GET"&&url.pathname==="/api/collections")return json(res,200,getAll());
 if(req.method==="POST"&&url.pathname==="/api/collections"){const input=await readBody(req),raw=String(input.raw_share_text||"").trim(),original=String(input.original_url||extractUrl(raw)),images=Array.isArray(input.images)?input.images.slice(0,9):[];if(!raw&&!original&&!input.title&&!images.length)return json(res,400,{error:"请粘贴分享文字、链接或选择图片"});const existing=original?db.prepare("SELECT * FROM collections WHERE user_id=? AND original_url=? LIMIT 1").get("local-user",original):(raw?db.prepare("SELECT * FROM collections WHERE user_id=? AND raw_share_text=? LIMIT 1").get("local-user",raw):null);if(existing)return json(res,200,{...normalize(existing),duplicate:true});const auto=classify(`${raw} ${input.title||""} ${input.ocr_text||""}`),now=new Date().toISOString(),title=String(input.title||raw.replace(/https?:\/\/\S+/g,"").replace(/复制此链接[\s\S]*/g,"").trim().slice(0,80)||(images.length?"图文收藏":"未命名收藏")),tags=input.tags?.length?input.tags:auto.tags,info={source:input.source||"douyin",content_type:input.content_type||inferContentType(raw,original),original_url:original,raw_share_text:raw,title,description:input.description||"",category:input.category||resolveCategory(auto.category),tags:JSON.stringify(tags),ocr_text:input.ocr_text||"",imported_at:now,created_at:now,parse_status:original?"saved_basic":"saved_without_url"};const result=db.prepare(`INSERT INTO collections (source,platform,content_type,original_url,raw_share_text,title,description,category,tags,ocr_text,imported_at,created_at,parse_status) VALUES (@source,@source,@content_type,@original_url,@raw_share_text,@title,@description,@category,@tags,@ocr_text,@imported_at,@created_at,@parse_status)`).run(info);for(const image of images){if(typeof image==="string"&&image.startsWith("data:image/")&&image.length<4_000_000)db.prepare("INSERT INTO collection_images (collection_id,data_url) VALUES (?,?)").run(result.lastInsertRowid,image);}return json(res,201,normalize(db.prepare("SELECT * FROM collections WHERE id=?").get(result.lastInsertRowid)));}
 if(req.method==="GET"&&url.pathname==="/api/stats"){const items=getAll(),monday=new Date();monday.setHours(0,0,0,0);monday.setDate(monday.getDate()-((monday.getDay()+6)%7));const week=items.filter(i=>new Date(i.imported_at)>=monday),byCategory=Object.fromEntries(getCategories().map(c=>[c.name,week.filter(i=>i.category===c.name).length]));return json(res,200,{total:items.length,thisWeek:week.length,byCategory,tags:[...new Set(items.flatMap(i=>i.tags))]});}
 if(req.method==="GET"&&url.pathname==="/api/categories")return json(res,200,getCategories());
 if(req.method==="POST"&&url.pathname==="/api/categories"){const input=await readBody(req),name=String(input.name||"").trim().slice(0,20);if(!name)return json(res,400,{error:"请输入分类名称"});try{const next=db.prepare("SELECT COALESCE(MAX(sort_order),-1)+1 AS value FROM categories WHERE user_id=?").get("local-user").value,result=db.prepare("INSERT INTO categories (user_id,name,rule_key,sort_order,created_at) VALUES (?,?,?,?,?)").run("local-user",name,null,next,new Date().toISOString());return json(res,201,db.prepare("SELECT id,name,rule_key,sort_order FROM categories WHERE id=?").get(result.lastInsertRowid));}catch{return json(res,409,{error:"这个分类已经存在"});}}
 const categoryMatch=url.pathname.match(/^\/api\/categories\/(\d+)$/);if(categoryMatch&&req.method==="PATCH"){const id=Number(categoryMatch[1]),current=db.prepare("SELECT * FROM categories WHERE id=? AND user_id=?").get(id,"local-user"),input=await readBody(req),name=String(input.name||"").trim().slice(0,20);if(!current)return json(res,404,{error:"分类不存在"});if(!name)return json(res,400,{error:"请输入分类名称"});try{db.exec("BEGIN");db.prepare("UPDATE collections SET category=? WHERE user_id=? AND category=?").run(name,"local-user",current.name);db.prepare("UPDATE categories SET name=? WHERE id=?").run(name,id);db.exec("COMMIT");return json(res,200,db.prepare("SELECT id,name,rule_key,sort_order FROM categories WHERE id=?").get(id));}catch(error){db.exec("ROLLBACK");return json(res,409,{error:"这个分类名称已经存在"});}}
 if(categoryMatch&&req.method==="DELETE"){const id=Number(categoryMatch[1]),current=db.prepare("SELECT * FROM categories WHERE id=? AND user_id=?").get(id,"local-user"),fallback=getCategories().find(x=>x.rule_key==="其他");if(!current)return json(res,404,{error:"分类不存在"});if(current.rule_key==="其他")return json(res,400,{error:"“其他”是兜底分类，不能删除"});db.exec("BEGIN");db.prepare("UPDATE collections SET category=? WHERE user_id=? AND category=?").run(fallback.name,"local-user",current.name);db.prepare("DELETE FROM categories WHERE id=?").run(id);db.exec("COMMIT");return json(res,200,{ok:true,moved_to:fallback.name});}
 if(req.method==="GET"&&url.pathname==="/api/search"){const terms=parseSearchQuery(url.searchParams.get("q")||""),items=getAll().map(item=>{const hay=`${item.title} ${item.description} ${item.raw_share_text} ${item.category} ${item.tags.join(" ")} ${item.ocr_text}`.toLowerCase();return{...item,_score:terms.reduce((s,t)=>s+(hay.includes(t)?1:0),0)}}).filter(i=>!terms.length||i._score>0).sort((a,b)=>b._score-a._score);return json(res,200,items);}
 if(req.method==="GET"&&url.pathname==="/api/review")return json(res,200,getAll().sort((a,b)=>reviewScore(b)-reviewScore(a)).slice(0,3));
 const match=url.pathname.match(/^\/api\/collections\/(\d+)(?:\/(review))?$/);if(match&&req.method==="PATCH"){const id=Number(match[1]);if(match[2])db.prepare("UPDATE collections SET review_count=review_count+1,last_reviewed_at=? WHERE id=?").run(new Date().toISOString(),id);else{const x=await readBody(req);db.prepare("UPDATE collections SET title=?,category=?,tags=?,ocr_text=? WHERE id=?").run(x.title,x.category,JSON.stringify(x.tags||[]),x.ocr_text||"",id);}return json(res,200,normalize(db.prepare("SELECT * FROM collections WHERE id=?").get(id)));}if(match&&req.method==="DELETE"){db.prepare("DELETE FROM collections WHERE id=?").run(Number(match[1]));return json(res,200,{ok:true});}return false;
}
const mime={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".svg":"image/svg+xml"};
http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host}`);if(url.pathname.startsWith("/api/")){if(await api(req,res,url)!==false)return;return json(res,404,{error:"未找到"});}const requested=url.pathname==="/"?"public/index.html":join("public",url.pathname),safe=requested.startsWith("public")&&existsSync(requested)?requested:"public/index.html",type=mime[extname(safe)]||"application/octet-stream";let content=await readFile(safe);if(safe.endsWith("index.html"))content=Buffer.from(content.toString().replace('src="/app.js"','src="/app.js?v=20260917-4"'));res.writeHead(200,{"content-type":type,"cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","expires":"0"});res.end(content);}catch(error){console.error(error);json(res,500,{error:"服务暂时不可用"});}}).listen(PORT,"127.0.0.1",()=>console.log(`拾藏 AI 已启动：http://127.0.0.1:${PORT}`));
