const cloudbase = require("@cloudbase/js-sdk");
const app = cloudbase.init({ env: "shicang-d5ghnihwq293cd52c" });
const db = app.database();
const DEFAULTS = [["AI", "AI"], ["找工作", "找工作"], ["美食", "美食"], ["小说", "小说"], ["其他", "其他"]];
const RULES = { AI: ["ai", "agent", "大模型", "人工智能", "langgraph", "rag", "编程", "开发", "模型"], 找工作: ["找工作", "求职", "面试", "简历", "招聘", "岗位", "offer", "职场"], 美食: ["美食", "餐厅", "小店", "探店", "好吃", "菜谱", "烹饪", "面馆", "咖啡"], 小说: ["小说", "网文", "书荒", "作者", "章节", "推文", "文学"] };
const extractUrl = (text = "") => (text.match(/https?:\/\/[^\s，。；！!）)]+/gi) || []).find((url) => /(?:v\.)?douyin\.com/i.test(url)) || "";
const searchTerms = (query = "") => query.toLowerCase().replace(/我|之前|以前|收藏过|哪些|有没有|帮我|找找|的|吗|？|\?/g, " ").split(/[\s，。]+/).filter((value) => value.length > 1);
const reviewScore = (item) => { const now = Date.now(), imported = new Date(item.imported_at).getTime(), last = item.last_reviewed_at ? new Date(item.last_reviewed_at).getTime() : imported; return Math.max(0, (now - imported) / 86400000) * 1.2 + Math.max(0, (now - last) / 86400000) * .8 - Number(item.review_count || 0) * 12; };
function classify(text = "") { const lower = text.toLowerCase(); let best = ["其他", 0]; for (const [name, words] of Object.entries(RULES)) { const score = words.filter((word) => lower.includes(word)).length; if (score > best[1]) best = [name, score]; } const hashtags = [...text.matchAll(/#\s*([^#\s，。！!]+)/g)].map((match) => match[1]); const keywords = Object.values(RULES).flat().filter((word) => lower.includes(word)); return { category: best[0], tags: [...new Set([...hashtags, ...keywords])].slice(0, 8) }; }
function userId(event, context) { return context?.userInfo?.uid || event?.userInfo?.uid || event?.userInfo?.openId || ""; }
async function list(name, user) { try { const result = await db.collection(name).where({ user_id: user }).limit(100).get(); return result.data || []; } catch (error) { if (/not exist|不存在|NOT_FOUND/i.test(String(error?.message || error))) { await db.createCollection(name); return []; } throw error; } }
async function ensureCategories(user) { const current = await list("categories", user); if (current.length) return current.sort((a, b) => a.sort_order - b.sort_order); const now = new Date().toISOString(); for (let index = 0; index < DEFAULTS.length; index += 1) await db.collection("categories").add({ user_id: user, name: DEFAULTS[index][0], rule_key: DEFAULTS[index][1], sort_order: index, created_at: now }); return list("categories", user); }
async function collections(user) { return (await list("collections", user)).sort((a, b) => String(b.imported_at).localeCompare(String(a.imported_at))); }
async function owned(name, id, user) { const result = await db.collection(name).doc(id).get(); const item = result.data?.[0]; return item && item.user_id === user ? item : null; }

exports.main = async (event, context) => {
  const user = userId(event, context); if (!user) return { error: "请先登录", status: 401 };
  const action = event.action, input = event.input || {};
  if (action === "me") return { user_id: user, name: "体验账号" };
  if (action === "collections") return collections(user);
  if (action === "categories") return ensureCategories(user);
  if (action === "createCollection") {
    const raw = String(input.raw_share_text || "").trim(), original = String(input.original_url || extractUrl(raw)), all = await collections(user);
    const duplicate = all.find((item) => original ? item.original_url === original : raw && item.raw_share_text === raw); if (duplicate) return { ...duplicate, duplicate: true };
    const auto = classify(`${raw} ${input.title || ""} ${input.ocr_text || ""}`), cats = await ensureCategories(user), category = input.category || cats.find((item) => item.rule_key === auto.category)?.name || "其他", now = new Date().toISOString();
    const images = Array.isArray(input.images) ? input.images.filter((value) => typeof value === "string" && value.startsWith("data:image/") && value.length < 900000).slice(0, 3) : [];
    const item = { user_id: user, source: input.source || "douyin", platform: input.source || "douyin", content_type: input.content_type || (/图文|图片|相册/.test(raw) ? "gallery" : original ? "video" : raw ? "text" : "unknown"), original_url: original, raw_share_text: raw, title: String(input.title || raw.replace(/https?:\/\/\S+/g, "").replace(/复制此链接[\s\S]*/g, "").trim().slice(0, 80) || (images.length ? "图文收藏" : "未命名收藏")), description: input.description || "", category, tags: input.tags?.length ? input.tags : auto.tags, ocr_text: input.ocr_text || "", images, imported_at: now, created_at: now, last_reviewed_at: null, review_count: 0, parse_status: original ? "saved_basic" : "saved_without_url", ai_summary: null, transcript: null, knowledge_items: null, embedding: null };
    const result = await db.collection("collections").add(item); return { ...item, _id: result.id, id: result.id };
  }
  if (action === "stats") { const all = await collections(user), cats = await ensureCategories(user), monday = new Date(); monday.setHours(0, 0, 0, 0); monday.setDate(monday.getDate() - ((monday.getDay() + 6) % 7)); const week = all.filter((item) => new Date(item.imported_at) >= monday); return { total: all.length, thisWeek: week.length, byCategory: Object.fromEntries(cats.map((cat) => [cat.name, week.filter((item) => item.category === cat.name).length])), tags: [...new Set(all.flatMap((item) => item.tags || []))] }; }
  if (action === "search") { const words = searchTerms(input.query || ""); return (await collections(user)).map((item) => { const hay = `${item.title} ${item.description} ${item.raw_share_text} ${item.category} ${(item.tags || []).join(" ")} ${item.ocr_text}`.toLowerCase(); return { ...item, _score: words.reduce((score, word) => score + (hay.includes(word) ? 1 : 0), 0) }; }).filter((item) => !words.length || item._score > 0).sort((a, b) => b._score - a._score); }
  if (action === "review") return (await collections(user)).sort((a, b) => reviewScore(b) - reviewScore(a)).slice(0, 3);
  if (action === "createCategory") { const name = String(input.name || "").trim().slice(0, 20), cats = await ensureCategories(user); if (!name) return { error: "请输入分类名称" }; if (cats.some((item) => item.name === name)) return { error: "这个分类已经存在" }; const item = { user_id: user, name, rule_key: null, sort_order: Math.max(-1, ...cats.map((cat) => cat.sort_order)) + 1, created_at: new Date().toISOString() }; const result = await db.collection("categories").add(item); return { ...item, id: result.id, _id: result.id }; }
  if (action === "updateCategory") { const item = await owned("categories", input.id, user), name = String(input.name || "").trim().slice(0, 20); if (!item || !name) return { error: "分类不存在或名称为空" }; for (const collection of (await collections(user)).filter((entry) => entry.category === item.name)) await db.collection("collections").doc(collection._id).update({ category: name }); await db.collection("categories").doc(input.id).update({ name }); return { ...item, name, id: item._id }; }
  if (action === "deleteCategory") { const item = await owned("categories", input.id, user); if (!item || item.rule_key === "其他") return { error: "该分类不能删除" }; const fallback = (await ensureCategories(user)).find((entry) => entry.rule_key === "其他"); for (const collection of (await collections(user)).filter((entry) => entry.category === item.name)) await db.collection("collections").doc(collection._id).update({ category: fallback.name }); await db.collection("categories").doc(input.id).remove(); return { ok: true, moved_to: fallback.name }; }
  if (action === "updateCollection") { const item = await owned("collections", input.id, user); if (!item) return { error: "收藏不存在" }; await db.collection("collections").doc(input.id).update({ title: input.title, category: input.category, tags: input.tags || [], ocr_text: input.ocr_text || "" }); return { ...item, ...input, _id: item._id, id: item._id }; }
  if (action === "reviewCollection") { const item = await owned("collections", input.id, user); if (!item) return { error: "收藏不存在" }; const next = { review_count: Number(item.review_count || 0) + 1, last_reviewed_at: new Date().toISOString() }; await db.collection("collections").doc(input.id).update(next); return { ...item, ...next, id: item._id }; }
  if (action === "deleteCollection") { const item = await owned("collections", input.id, user); if (item) await db.collection("collections").doc(input.id).remove(); return { ok: true }; }
  return { error: "未找到操作" };
};
